app/tickets/authentication/urls.py
from django.conf.urls import url
from tickets.authentication.views import LoginView, RegistrationView, LogoutView


app_name = 'authentication'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
]

app/tickets/core/urls.py
from django.conf.urls import url
from tickets.core.views import MainView

app_name = 'core'

urlpatterns = [
    url(r'^$', MainView.as_view(), name='home'),
]

app/tickets/tickets/urls.py
from django.conf.urls import url

from tickets.tickets.views import ListTicketsView, CreateTicketView, ViewTicketView, EditTicketView

app_name = 'tickets'

urlpatterns = [
    url(r'^$', ListTicketsView.as_view(), name='list'),
    url(r'^create/$', CreateTicketView.as_view(), name='create'),
    url(r'^view/(?P<pk>[0-9]+)/$', ViewTicketView.as_view(), name='view'),
    url(r'^edit/(?P<pk>[0-9]+)/$', EditTicketView.as_view(), name='edit'),
]

app/tickets/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('tickets.authentication.urls', namespace='authentication')),
    url(r'^tickets/', include('tickets.tickets.urls', namespace='tickets')),
    url(r'^comments/', include('tickets.comments.urls', namespace='comments')),
    url(r'', include('tickets.core.urls', namespace='core')),
]

app/tickets/core/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View

from tickets.tickets.models import Ticket, TICKET_STATUS_FINISHED

User = get_user_model()


class MainView(View):
    template_name = 'main/main.html',

    def get(self, request):
        current_user = request.user

        context = {
            'is_authenticated': current_user.is_authenticated,
            'user': current_user
        }

        if current_user.is_authenticated:
            # fetch all tickets of that user
            tickets = Ticket.objects.filter(assigned_to=current_user).exclude(status__in=[
                TICKET_STATUS_FINISHED
            ])
            context.update({'your_tickets': tickets})

        return render(request, self.template_name, context)

app/tickets/core/templates/main/main.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Welcome to the Ticket System" %}
{% endblock %}

{% block content %}
    {% if not is_authenticated %}
        {% blocktrans trimmed %}
            <p>You are not authenticated!</p>
        {% endblocktrans %}
        <ul>
            <li>
                <a href="{% url 'authentication:login' %}">{% trans "Login" %}</a>
            </li>
            <li>
                <a href="{% url 'authentication:registration' %}">{% trans "Sign up" %}</a>
            </li>
        </ul>

    {% else %}
        <p>{%  trans "Welcome! Please have a look at the tickets!" %}</p>

        <p><b>{%  trans "You are currently responsible for the following tickets:" %}</b></p>

        <ul>
            {% for ticket in your_tickets %}
                <li><a href="{% url 'tickets:view' ticket.pk %}">{{ ticket }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}