app/tickets/authentication/urls.py
from django.conf.urls import url
from tickets.authentication.views import LoginView, RegistrationView, LogoutView


app_name = 'authentication'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
]

app/tickets/core/urls.py
from django.conf.urls import url
from tickets.core.views import MainView

app_name = 'core'

urlpatterns = [
    url(r'^$', MainView.as_view(), name='home'),
]

app/tickets/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('tickets.authentication.urls', namespace='authentication')),
    url(r'^tickets/', include('tickets.tickets.urls', namespace='tickets')),
    url(r'^comments/', include('tickets.comments.urls', namespace='comments')),
    url(r'', include('tickets.core.urls', namespace='core')),
]

app/tickets/core/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View

from tickets.tickets.models import Ticket, TICKET_STATUS_FINISHED

User = get_user_model()


class MainView(View):
    template_name = 'main/main.html',

    def get(self, request):
        current_user = request.user

        context = {
            'is_authenticated': current_user.is_authenticated,
            'user': current_user
        }

        if current_user.is_authenticated:
            # fetch all tickets of that user
            tickets = Ticket.objects.filter(assigned_to=current_user).exclude(status__in=[
                TICKET_STATUS_FINISHED
            ])
            context.update({'your_tickets': tickets})

        return render(request, self.template_name, context)

app/tickets/core/templates/base.html
{% load i18n is_active staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# include bootstrap #}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {# page title #}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<!-- Static navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'core:home' %}">
                {% trans "Ticket Management Demo App" %}
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="{% is_active 'core:home' %}">
                    <a href="{% url 'core:home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="{% is_active 'tickets:list' %}">
                        <a href="{% url 'tickets:list' %}">Tickets</a>
                    </li>

{#                    <li class="dropdown">#}
{#                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">#}
{#                            Dropdown <span class="caret"></span>#}
{#                        </a>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a href="#">Action</a></li>#}
{#                            <li><a href="#">Another action</a></li>#}
{#                            <li><a href="#">Something else here</a></li>#}
{#                            <li role="separator" class="divider"></li>#}
{#                            <li class="dropdown-header">Nav header</li>#}
{#                            <li><a href="#">Separated link</a></li>#}
{#                            <li><a href="#">One more separated link</a></li>#}
{#                        </ul>#}
{#                    </li>#}
                {% else %}
                    <li>
                        <a href="{% url 'authentication:registration' %}">
                            Sign Up
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {# ToDo: Show current user as a dropdown #}
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'authentication:logout' %}">{% trans "Logout" %}</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'authentication:login' %}">{% trans "Login" %}</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<a href="https://github.com/ChristianKreuzberger">
    <img style="position: absolute; top: 0; left: 0; border: 0; z-index: 10000"
         src="{% static "forkme_left_red_aa0000.png" %}" alt="Fork me on GitHub">
</a>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>