app/tickets/comments/urls.py
from django.conf.urls import url

from tickets.comments.views import CreateCommentView

app_name = 'comments'

urlpatterns = [
    url(r'^view/(?P<pk>[0-9]+)/create_comment$', CreateCommentView.as_view(), name='create'),
]

app/tickets/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('tickets.authentication.urls', namespace='authentication')),
    url(r'^tickets/', include('tickets.tickets.urls', namespace='tickets')),
    url(r'^comments/', include('tickets.comments.urls', namespace='comments')),
    url(r'', include('tickets.core.urls', namespace='core')),
]

app/tickets/comments/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class Comment(models.Model):
    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ('created_at',)

    text = models.TextField(
        verbose_name=_("Comment")
    )

    ticket = models.ForeignKey(
        'tickets.Ticket',
        verbose_name=_("Which ticket is this comment for"),
        on_delete=models.CASCADE,
        related_name='comments',
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="comments_created_by_user",
        verbose_name=_("Who created the comment"),
        on_delete=models.CASCADE
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("When was the comment created"),
        db_index=True
    )

    def __str__(self):
        return _("Comment from %(date)s on ticket %(ticket)s") % {'date': self.created_at, 'ticket': self.ticket}

app/tickets/comments/forms.py
from django import forms

from tickets.comments.models import Comment


class CreateCommentForm(forms.ModelForm):
    """
    Provides a form for creating a new comment on a ticket
    """

    class Meta:
        model = Comment
        fields = ('text', )

app/tickets/comments/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import View

from tickets.comments.forms import CreateCommentForm
from tickets.tickets.models import Ticket


class CreateCommentView(View):
    """
    View for creating a new comment on a ticket
    """

    template_name = 'comments/create.html'

    def get(self, request, pk, *args, **kwargs):
        ticket = get_object_or_404(Ticket.objects.all(), pk=pk)

        create_comment_form = CreateCommentForm()

        context = {
            'ticket': ticket,
            'create_comment_form': create_comment_form
        }

        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        ticket = get_object_or_404(Ticket.objects.all(), pk=pk)

        create_comment_form = CreateCommentForm(
            request.POST or None
        )

        context = {
            'ticket': ticket,
            'create_comment_form': create_comment_form
        }

        current_user = request.user

        if create_comment_form.is_valid():
            comment = create_comment_form.save(commit=False)
            comment.ticket = ticket
            comment.created_by = current_user
            comment.save()

            # on success, redirect to the ticket detail view
            return HttpResponseRedirect(reverse('tickets:view', kwargs={'pk': pk}))

        return render(request, self.template_name, context)

app/tickets/comments/templates/comments/create.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Create Ticket" %}
{% endblock %}

{% block content %}

    <h3>{% blocktrans %}You are commenting on '{{ ticket }}'{% endblocktrans %}</h3>

    <form action="{% url "comments:create" ticket.pk %}" method="post"
          class="form-horizontal">
        {% csrf_token %}

        <p class="help">
            {{ create_comment_form.non_field_errors }}
        </p>

        {% for field in create_comment_form %}
            <div class="form-group">
                <label class="col-sm-3">
                    {{ field.label_tag }}
                </label>
                <div class="col-sm-9">
                    {{ field }}
                    <br />

                    {{ field.errors }}

                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

        <input type="submit" value="Create new Comment" />
    </form>
{% endblock %}

app/tickets/comments/templates/comments/create_inline.html
{{ form }}

app/tickets/comments/templates/comments/ticket_comments.html
{# display all comments of the provided ticket #}
{% for comment in ticket.comments.all %}
    <div class="panel panel-default">
        <div class="panel-heading">
            {{ comment.created_by }} commented at {{ comment.created_at }}:
        </div>
        <div class="panel-body">
            {{ comment.text | linebreaksbr }}

        </div>
    </div>
{% endfor %}